# -*- encoding: utf-8 -*-
"""
@Id :__init__.py
@date :2025/06/16 15:59:13
@author :YenochQin (秦毅)
"""

__author__ = "YenochQin (秦毅)"

from .version import __version__
from .utils import fig_settings

from .data_IO import (
    GraspFileLoad,
    EnergyFile2csv,
    write_sorted_CSFs_to_cfile,
    write_CSFs_pl_to_cfile,
    save_csf_metadata,
    save_csfs_binary,
    continue_calculate,
    update_config,
    pkl_storage,
    precompute_large_hash,
    save_descriptors,
    save_descriptors_with_multi_block,
    load_csf_metadata,
    load_csfs_binary,
    pkl_loader,
    load_large_hash,
    load_config,
    load_descriptors,
    load_descriptors_with_multi_block,
    CppDescriptorGenerator,
    batch_process_csfs_with_multi_block_cpp,
    load_hdf5_descriptors,
)

from .utils import (
    MixCoefficientData,
    CSFs,
    level_print_title,
    level_J_value,
    level_parity,
    energy_au_cm,
    align_2d_list_columns,
    int_nl_2_str_nl,
    str_subshell_2_kappa,
    doubleJ_to_J,
    read_fortran_record,
    chunk_string,
    level_data_compare,
    get_environment_config,
    is_slurm_environment,
    is_debug_mode,
    is_production_mode,
    create_progress_bar,
    wrap_iterator,
    progress_range,
    progress_context,
    log_stage_start,
    log_stage_end,
    calculate_deformation,
    LS_shell_full_charged,
    inter_coupling_channel_bar,
    auto_plot_wavefunction_comparison,
)

from .CSFs_processor import (
    batch_asfs_mix_square_above_threshold,
    asf_mix_square_above_threshold_coupling_info,
    CSFs_block_get_CSF,
    batch_blocks_csfs_final_coupling_J_collection,
    single_asf_csfs_final_coupling_J_mix_coefficient_sum,
    single_block_batch_asfs_CSFs_final_coupling_J_collection,
    batch_blocks_CSFs_final_coupling_J_mix_coefficient_sum,
    block_csfs_coupling_J_chosen,
    union_lists_with_order,
    merge_multiple_dicts_with_ordered_union,
    merge_csfs_idxs_lists_by_block_key,
    CSFs_sort_by_mix_coefficient,
    generate_unique_random_numbers,
    radom_choose_csfs,
    process_block,
    maping_two_csfs_idxs,
    csf_J,
    J_to_doubleJ,
    CSF_info_2_dict,
    CSF_item_2_dict,
    get_CSFs_file_info,
    parse_csf_2_descriptor,
    batch_process_csfs_to_descriptors,
    batch_process_csfs_parquet_to_descriptors
)

from .grasp_data_extractor import (
    ConfigurationFormatter,
    LevelsEnergyData,
    mcdhf_energy_data_collection,
    ci_energy_data_collection,
    level_energy_collector,
    LevelsASFComposition,
    asf_radial_wavefunction_collection,
    RadialElectrondensityFunction,
    TransitionDataCollection,
    LSJTransitionDataCollection,
    LSJTransitionDataBlock,
    TransitionDataBlock,
    data_process,
    lsj_transition_data_level_location,
    transition_data_level_location,
    transition_dT_cal,
)

from .ml_module import (
    ANNClassifier,
    setup_config,
    setup_logging,
    setup_directories,
    initialize_iteration_results_csv,
    training_data_loader,
    check_configuration_coupling,
    generate_train_csfs_descriptors,
    get_stay_descriptors,
    train_model,
    evaluate_model,
    save_iteration_results,
    check_energy_convergence,
    evaluate_calculation_convergence,
    handle_calculation_error,
    save_and_plot_results,
    validate_csf_descriptors_coverage,
    select_csfs_for_coverage,
)

__all__ = [
    # 版本信息
    "__author__",
    "__version__",
    # data_IO
    ## grasp_raw_data_load
    "GraspFileLoad",
    "EnergyFile2csv",
    ## produced_data_write
    "write_sorted_CSFs_to_cfile",
    "write_CSFs_pl_to_cfile",
    "save_csf_metadata",
    "save_csfs_binary",
    "continue_calculate",
    "update_config",
    "pkl_storage",
    "precompute_large_hash",
    "save_descriptors",
    "save_descriptors_with_multi_block",
    ## processing_data_load
    "load_csf_metadata",
    "load_csfs_binary",
    "pkl_loader",
    "load_large_hash",
    "load_config",
    "load_descriptors",
    "load_descriptors_with_multi_block",
    "CppDescriptorGenerator",
    "batch_process_csfs_with_multi_block_cpp",
    "load_hdf5_descriptors",
    # utils
    "MixCoefficientData",
    "CSFs",
    # 工具函数
    "level_print_title",
    "level_J_value",
    "level_parity",
    "energy_au_cm",
    "align_2d_list_columns",
    "int_nl_2_str_nl",
    "str_subshell_2_kappa",
    "doubleJ_to_J",

    "read_fortran_record",
    "chunk_string",
    "level_data_compare",
    "calculate_deformation",
    "LS_shell_full_charged",
    ## CSFs_processor
    "batch_asfs_mix_square_above_threshold",
    "asf_mix_square_above_threshold_coupling_info",
    "CSFs_block_get_CSF",
    "batch_blocks_csfs_final_coupling_J_collection",
    "single_asf_csfs_final_coupling_J_mix_coefficient_sum",
    "single_block_batch_asfs_CSFs_final_coupling_J_collection",
    "batch_blocks_CSFs_final_coupling_J_mix_coefficient_sum",
    "block_csfs_coupling_J_chosen",
    "union_lists_with_order",
    "merge_multiple_dicts_with_ordered_union",
    "merge_csfs_idxs_lists_by_block_key",
    "CSFs_sort_by_mix_coefficient",
    "generate_unique_random_numbers",
    "radom_choose_csfs",
    "process_block",
    "maping_two_csfs_idxs",
    ## CSFs_compress_extract
    "csf_J",
    "J_to_doubleJ",
    "CSF_info_2_dict",
    "CSF_item_2_dict",
    "get_CSFs_file_info",
    "parse_csf_2_descriptor",
    "batch_process_csfs_to_descriptors",
    "batch_process_csfs_parquet_to_descriptors",
    # grasp_data_extractor
    "ConfigurationFormatter",
    "LevelsEnergyData",
    "mcdhf_energy_data_collection",
    "ci_energy_data_collection",
    "level_energy_collector",
    "LevelsASFComposition",
    "asf_radial_wavefunction_collection",
    "RadialElectrondensityFunction",
    "TransitionDataCollection",
    "LSJTransitionDataCollection",
    "LSJTransitionDataBlock",
    "TransitionDataBlock",
    "data_process",
    # transition_data_analyzer
    'lsj_transition_data_level_location',
    'transition_data_level_location',
    'transition_dT_cal',
    
    # ml_module
    # neural_network
    "ANNClassifier",
    # ml_initializer
    "setup_config",
    "setup_logging",
    "setup_directories",
    "initialize_iteration_results_csv",
    "training_data_loader",
    "check_configuration_coupling",
    "check_energy_convergence",
    "evaluate_calculation_convergence",
    "generate_train_csfs_descriptors",
    "get_stay_descriptors",
    # ml_trainer
    "train_model",
    "evaluate_model",
    "handle_calculation_error",
    # ml_results_analyzer
    "validate_csf_descriptors_coverage",
    "select_csfs_for_coverage",
    "save_iteration_results",
    "save_and_plot_results",
    # 环境配置和进度管理
    "get_environment_config",
    "is_slurm_environment",
    "is_debug_mode",
    "is_production_mode",
    "create_progress_bar",
    "wrap_iterator",
    "progress_range",
    "progress_context",
    "log_stage_start",
    "log_stage_end",

    # 作图
    "inter_coupling_channel_bar",
    "auto_plot_wavefunction_comparison"
]
