# -*- encoding: utf-8 -*-
"""
@Id :__init__.py
@date :2025/06/16 15:59:13
@author :YenochQin (秦毅)
"""

__author__ = "YenochQin (秦毅)"

from .CSFs_processor import (
    CSF_info_2_dict,
    CSF_item_2_dict,
    CSFs_block_get_CSF,
    CSFs_sort_by_mix_coefficient,
    J_to_doubleJ,
    asf_mix_square_above_threshold_coupling_info,
    batch_asfs_mix_square_above_threshold,
    batch_blocks_csfs_final_coupling_J_collection,
    batch_blocks_CSFs_final_coupling_J_mix_coefficient_sum,
    batch_process_csfs_parquet_to_descriptors,
    batch_process_csfs_to_descriptors,
    block_csfs_coupling_J_chosen,
    csf_J,
    generate_unique_random_numbers,
    get_CSFs_file_info,
    maping_two_csfs_idxs,
    merge_csfs_idxs_lists_by_block_key,
    merge_multiple_dicts_with_ordered_union,
    parse_csf_2_descriptor,
    process_block,
    radom_choose_csfs,
    single_asf_csfs_final_coupling_J_mix_coefficient_sum,
    single_block_batch_asfs_CSFs_final_coupling_J_collection,
    union_lists_with_order,
)
from .data_IO import (
    BaseLoader,
    BinaryFileLoader,
    CppDescriptorGenerator,
    CSFLoader,
    EnergyFileLoader,
    LSJCompLoader,
    MixCoefLoader,
    RWFNFileLoader,
    TransitionLoader,
    batch_process_csfs_with_multi_block_cpp,
    continue_calculate,
    load_config,
    load_csf_metadata,
    load_csfs_binary,
    load_descriptors,
    load_descriptors_with_multi_block,
    load_hdf5_descriptors,
    load_large_hash,
    pkl_loader,
    pkl_storage,
    precompute_large_hash,
    save_csf_metadata,
    save_csfs_binary,
    save_descriptors,
    save_descriptors_with_multi_block,
    scan_descriptors_polars,
    update_config,
    write_CSFs_pl_to_cfile,
    write_sorted_CSFs_to_cfile,
)
from .grasp_data_extractor import (
    format_compositions,
    format_configuration,
    format_energy_configurations,
    iterative_levels_collection,
    level_energy_collector,
    level_transition_data_processing,
    lsj_transition_data_level_location,
    merge_lsj_compositions,
    transition_data_level_location,
)
from .ml_module import (
    ANNClassifier,
    check_configuration_coupling,
    check_energy_convergence,
    ci_idx_data_processor,
    evaluate_calculation_convergence,
    evaluate_model,
    generate_train_csfs_descriptors,
    get_stay_descriptors,
    handle_calculation_error,
    ml_results_statistics,
    predict_model,
    save_and_plot_results,
    save_iteration_results,
    select_csfs_for_coverage,
    setup_config,
    setup_directories,
    setup_logging,
    train_model,
    training_data_loader,
    validate_csf_desc_coverage,
)
from .utils import (
    CSFs,
    LS_shell_full_charged,
    MixCoefficientData,
    MLDataCounts,
    align_2d_list_columns,
    auto_plot_wavefunction_comparison,
    calculate_deformation,
    chunk_string,
    create_progress_bar,
    doubleJ_to_J,
    fig_settings,
    get_environment_config,
    int_nl_2_str_nl,
    inter_coupling_channel_bar,
    is_debug_mode,
    is_production_mode,
    is_slurm_environment,
    level_data_compare,
    log_stage_end,
    log_stage_start,
    progress_context,
    progress_range,
    str_subshell_2_kappa,
    wrap_iterator,
)
from .version import __version__

__all__ = [
    # 版本信息
    "__author__",
    "__version__",
    # data_IO
    ## new loaders
    "BaseLoader",
    "BinaryFileLoader",
    "CSFLoader",
    "EnergyFileLoader",
    "LSJCompLoader",
    "MixCoefLoader",
    "RWFNFileLoader",
    "TransitionLoader",
    ## produced_data_write
    "write_sorted_CSFs_to_cfile",
    "write_CSFs_pl_to_cfile",
    "save_csf_metadata",
    "save_csfs_binary",
    "continue_calculate",
    "update_config",
    "pkl_storage",
    "precompute_large_hash",
    "save_descriptors",
    "save_descriptors_with_multi_block",
    ## processing_data_load
    "load_csf_metadata",
    "load_csfs_binary",
    "pkl_loader",
    "load_large_hash",
    "load_config",
    "load_descriptors",
    "scan_descriptors_polars",
    "load_descriptors_with_multi_block",
    "CppDescriptorGenerator",
    "batch_process_csfs_with_multi_block_cpp",
    "load_hdf5_descriptors",
    # utils
    "MixCoefficientData",
    "CSFs",
    "MLDataCounts",
    # 工具函数
    "align_2d_list_columns",
    "int_nl_2_str_nl",
    "str_subshell_2_kappa",
    "doubleJ_to_J",
    "chunk_string",
    "level_data_compare",
    "calculate_deformation",
    "LS_shell_full_charged",
    ## CSFs_processor
    "batch_asfs_mix_square_above_threshold",
    "asf_mix_square_above_threshold_coupling_info",
    "CSFs_block_get_CSF",
    "batch_blocks_csfs_final_coupling_J_collection",
    "single_asf_csfs_final_coupling_J_mix_coefficient_sum",
    "single_block_batch_asfs_CSFs_final_coupling_J_collection",
    "batch_blocks_CSFs_final_coupling_J_mix_coefficient_sum",
    "block_csfs_coupling_J_chosen",
    "union_lists_with_order",
    "merge_multiple_dicts_with_ordered_union",
    "merge_csfs_idxs_lists_by_block_key",
    "CSFs_sort_by_mix_coefficient",
    "generate_unique_random_numbers",
    "radom_choose_csfs",
    "process_block",
    "maping_two_csfs_idxs",
    ## CSFs_compress_extract
    "csf_J",
    "J_to_doubleJ",
    "CSF_info_2_dict",
    "CSF_item_2_dict",
    "get_CSFs_file_info",
    "parse_csf_2_descriptor",
    "batch_process_csfs_to_descriptors",
    "batch_process_csfs_parquet_to_descriptors",
    # grasp_data_extractor
    "format_configuration",
    "format_energy_configurations",
    "format_compositions",
    "iterative_levels_collection",
    "level_energy_collector",
    "merge_lsj_compositions",
    "lsj_transition_data_level_location",
    "transition_data_level_location",
    "level_transition_data_processing",
    # ml_module
    # neural_network
    "ANNClassifier",
    # ml_initializer
    "setup_config",
    "setup_logging",
    "setup_directories",
    "training_data_loader",
    "ci_idx_data_processor",
    "check_configuration_coupling",
    "check_energy_convergence",
    "evaluate_calculation_convergence",
    "generate_train_csfs_descriptors",
    "get_stay_descriptors",
    # ml_trainer
    "train_model",
    "evaluate_model",
    "predict_model",
    "handle_calculation_error",
    # ml_results_analyzer
    "validate_csf_desc_coverage",
    "select_csfs_for_coverage",
    "save_iteration_results",
    "save_and_plot_results",
    "ml_results_statistics",
    # 环境配置和进度管理
    "get_environment_config",
    "is_slurm_environment",
    "is_debug_mode",
    "is_production_mode",
    "create_progress_bar",
    "wrap_iterator",
    "progress_range",
    "progress_context",
    "log_stage_start",
    "log_stage_end",
    # 作图
    "inter_coupling_channel_bar",
    "auto_plot_wavefunction_comparison",
]
